---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /workdir

steps:
  - name: mavenBuildDev
    pull: always
    image: meltwaterfoundation/drone-maven-jdk8
    commands:
      - echo 'Build and test.'
      - mvn -U -B clean package
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    when:
      event:
        - push

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
